name: Chris Ledger Photography
favicon: null
layout_spectrum: 0.87597
typography_spectrum: 0.45677
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8d4d2a'
    - '#49200c'
    - '#c58851'
    - '#c7ac7d'
    - '#110c09'
  brandStrength: 0.1875
  lightness: 0.5290118323173374
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
